# Generated by Django 4.2.3 on 2024-09-07 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('anno_academico', models.IntegerField()),
                ('CI', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')])),
                ('telefono', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('programacion', 'Programacion'), ('matematica', 'Matematica'), ('sistemas operativos', 'Sistemas operativos'), ('ingenieria de software', 'Ingenieria de software'), ('compilacion', 'Compilacion'), ('redes de computadoras', 'Redes de computadoras'), ('estadistica', 'Estadistica'), ('letras', 'Letras'), ('investigacion de operaciones', 'Investigacion de operaciones'), ('inteligencia artificial', 'Inteligencia artificial'), ('bases de datos', 'Bases de datos')], max_length=30)),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_prestada', models.IntegerField()),
                ('autor', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libro')),
            ],
        ),
    ]
