# Generated by Django 4.2.3 on 2024-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('programacion', 'Programación'), ('matematica', 'Matemática'), ('sistemas operativos', 'Sistemas operativos'), ('ingenieria de software', 'Ingeniería de software'), ('compilacion', 'Compilación'), ('redes de computadoras', 'Redes de computadoras'), ('estadistica', 'Estadística'), ('letras', 'Letras'), ('investigacion de operaciones', 'Investigación de operaciones'), ('inteligencia artificial', 'Inteligencia artificial'), ('bases de datos', 'Bases de datos')], max_length=30),
        ),
    ]
